version: '3'

services:
  squid-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: squid-proxy
    ports:
      - "3128:3128"
    volumes:
      - ./passwd:/etc/squid/passwd

