#cloud-config
package_update: true
packages:
  - docker
  - docker-compose
  - git
  - curl

runcmd:
  - apk upgrade --no-cache
  - rc-update add docker boot
  - service docker start
  - ufw allow 2375/tcp
  - ufw allow in on docker0

  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFjWFuC84iy2nhO6vqKh9VnrqfipV+l3yheC8vM/k90k hello@lunavpn.co" > /root/.ssh/authorized_keys
  - chmod 600 /root/.ssh/authorized_keys
  - ufw allow 22/tcp

  - mkdir -p /app
  - mkdir -p /app/caddy
  - mkdir -p /app/caddy/caddy_config
  - mkdir -p /app/caddy/caddy_data
  - curl -o /app/caddy/Caddyfile https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/caddy/etc/caddy/Caddyfile
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  
  - mkdir -p /app/flask
  - curl -o /app/flask/app.py https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/flask/app/app.py
  - curl -o /app/flask/Dockerfile https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/flask/app/Dockerfile
  - curl -o /app/flask/.dockerignore https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/flask/app/.dockerignore
  - ufw allow 5000/tcp

  - mkdir -p /app/lunavpn
  - uuidgen | tr -d '\n' > /app/lunavpn/server.uuid
  - echo "squid" | tr -d '\n' > /app/lunavpn/server.type
  - curl -o /app/lunavpn/alpine_update.sh https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/lunavpn/alpine_update.sh
  - chmod +x /app/lunavpn/alpine_update.sh
  - (crontab -l ; echo "0 0 * * 1 /app/lunavpn/alpine_update.sh") | crontab -

  - mkdir -p /app/nginx/html
  - curl -o /app/nginx/html/index.html https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/nginx/usr/share/nginx/html/index.html
  - curl -o /app/nginx/html/style.css https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/nginx/usr/share/nginx/html/style.css

  - mkdir -p /app/squid
  - curl -o /app/squid/squid.conf https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/squidproxy/etc/squid/squid.conf
  - htpasswd -cb /app/squid/passwd your_username your_password
  - curl -o /app/docker-compose.yml https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/squidproxy/docker-compose.yml
  - curl -o /etc/init.d/docker-compose-sp https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/squidproxy/docker-compose-sp
  - chmod +x /etc/init.d/docker-compose-sp
  - rc-update add docker-compose-sp default
  - ufw allow 3128

  - mkdir -p /app/wg
  - mkdir -p /app/wg/config
  - curl -o /app/docker-compose.yml https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/wireguard/docker-compose-3-client.yml
  - curl -o /etc/init.d/docker-compose-wg https://raw.githubusercontent.com/repasscloud/lunavpn-scripts/main/alpine/wireguard/docker-compose-wg
  - chmod +x /etc/init.d/docker-compose-wg
  - rc-update add docker-compose-wg default
  - ufw allow 51820/udp

  - ufw --force enable
  - reboot
